[build]
  publish = "."

[[redirects]]
  from = "/application"
  to = "/application.html"
  status = 200

[[redirects]]
  from = "/application/gamingandsports"
  to = "/application/gamingandsports.html"
  status = 200

