[build]
  publish = "."

[[redirects]]
  from = "/technical"
  to = "/technical.html"
  status = 200

[[redirects]]
  from = "/application"
  to = "/application.html"
  status = 200


[[redirects]]
  from = "/application/technical"
  to = "/application/technical.html"
  status = 200

[[redirects]]
  from = "/gaming-sports/round1"
  to = "/gaming-sports/round1.html"
  status = 200
